import json
import os

notebook_path = r"c:\Users\HP\Documents\GitHub\ML-dating-app-behaviour\notebooks\ML_dating_app_behaviour V3.ipynb"

# Read the notebook
with open(notebook_path, "r", encoding="utf-8") as f:
    nb = json.load(f)

# Define the new source code for cell 39
new_source = [
    "# --- ADVANCED DIFFERENTIAL NEURAL ARCHITECTURES & SKLEARN WRAPPER ---\n",
    "import os\n",
    "import numpy as np\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.optim as optim\n",
    "from torch.utils.data import TensorDataset, DataLoader\n",
    "from sklearn.base import BaseEstimator, ClassifierMixin\n",
    "\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.neighbors import KNeighborsClassifier\n",
    "from sklearn.tree import DecisionTreeClassifier\n",
    "from sklearn.ensemble import RandomForestClassifier, BaggingClassifier\n",
    "from sklearn.svm import SVC\n",
    "from sklearn.neural_network import MLPClassifier\n",
    "from lightgbm import LGBMClassifier\n",
    "from catboost import CatBoostClassifier\n",
    "from imblearn.ensemble import BalancedRandomForestClassifier\n",
    "try:\n",
    "    from xgboost import XGBClassifier\n",
    "except ImportError:\n",
    "    from sklearn.ensemble import GradientBoostingClassifier as XGBClassifier\n",
    "\n",
    "# Ensure TREE_CONFIG, DEVICE, and RANDOM_STATE are defined in globals\n",
    "if 'TREE_CONFIG' not in globals():\n",
    "    TREE_CONFIG = {\n",
    "        'xgb': {'device': 'cpu', 'tree_method': 'hist'},\n",
    "        'lgb': {'device_type': 'cpu'}\n",
    "    }\n",
    "if 'DEVICE' not in globals():\n",
    "    DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
    "if 'RANDOM_STATE' not in globals():\n",
    "    RANDOM_STATE = 42\n",
    "\n",
    "# 1. FT-Transformer (Feature Tokenizer Transformer)\n",
    "class FeatureTokenizer(nn.Module):\n",
    "    def __init__(self, num_numeric, cat_vocab_sizes, d_token):\n",
    "        super().__init__()\n",
    "        self.cat_embeddings = nn.ModuleList([\n",
    "            nn.Embedding(vocab_size, d_token) for vocab_size in cat_vocab_sizes\n",
    "        ])\n",
    "        self.num_projections = nn.ModuleList([\n",
    "            nn.Linear(1, d_token) for _ in range(num_numeric)\n",
    "        ])\n",
    "        \n",
    "    def forward(self, x_num, x_cat):\n",
    "        tokens = []\n",
    "        for i, emb in enumerate(self.cat_embeddings):\n",
    "            tokens.append(emb(x_cat[:, i]).unsqueeze(1))\n",
    "        for i, proj in enumerate(self.num_projections):\n",
    "            tokens.append(proj(x_num[:, i].unsqueeze(1)).unsqueeze(1))\n",
    "        return torch.cat(tokens, dim=1) if tokens else torch.zeros(x_num.size(0), 0, d_token, device=x_num.device)\n",
    "\n",
    "class FTTransformer(nn.Module):\n",
    "    def __init__(self, num_numeric, cat_vocab_sizes, d_token=32, n_layers=2, n_heads=4, d_ff=64):\n",
    "        super().__init__()\n",
    "        self.tokenizer = FeatureTokenizer(num_numeric, cat_vocab_sizes, d_token)\n",
    "        encoder_layer = nn.TransformerEncoderLayer(\n",
    "            d_model=d_token, nhead=n_heads, dim_feedforward=d_ff,\n",
    "            activation='gelu', batch_first=True\n",
    "        )\n",
    "        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=n_layers)\n",
    "        self.head = nn.Sequential(\n",
    "            nn.LayerNorm(d_token),\n",
    "            nn.ReLU(),\n",
    "            nn.Linear(d_token, 1)\n",
    "        )\n",
    "        \n",
    "    def forward(self, x_num, x_cat):\n",
    "        tokens = self.tokenizer(x_num, x_cat)\n",
    "        encoded = self.transformer(tokens)\n",
    "        pooled = encoded.mean(dim=1)\n",
    "        return self.head(pooled).squeeze(-1)\n",
    "\n",
    "# 2. SAINT (Self-Attention and Invariant Representation)\n",
    "class SAINT(nn.Module):\n",
    "    def __init__(self, num_numeric, cat_vocab_sizes, d_token=32, n_layers=2, n_heads=4):\n",
    "        super().__init__()\n",
    "        self.tokenizer = FeatureTokenizer(num_numeric, cat_vocab_sizes, d_token)\n",
    "        self.attn_layers = nn.ModuleList([\n",
    "            nn.MultiheadAttention(embed_dim=d_token, num_heads=n_heads, batch_first=True)\n",
    "            for _ in range(n_layers)\n",
    "        ])\n",
    "        self.norms = nn.ModuleList([nn.LayerNorm(d_token) for _ in range(n_layers)])\n",
    "        self.ffn = nn.Sequential(\n",
    "            nn.Linear(d_token, d_token),\n",
    "            nn.ReLU(),\n",
    "            nn.Linear(d_token, d_token)\n",
    "        )\n",
    "        self.head = nn.Linear(d_token, 1)\n",
    "        \n",
    "    def forward(self, x_num, x_cat):\n",
    "        x = self.tokenizer(x_num, x_cat)\n",
    "        for attn, norm in zip(self.attn_layers, self.norms):\n",
    "            residual = x\n",
    "            x, _ = attn(x, x, x)\n",
    "            x = norm(x + residual)\n",
    "        pooled = x.mean(dim=1)\n",
    "        return self.head(pooled).squeeze(-1)\n",
    "\n",
    "# 3. NODE (Neural Oblivious Decision Ensembles)\n",
    "class ObliviousDecisionTree(nn.Module):\n",
    "    def __init__(self, in_features, depth=3, d_out=1):\n",
    "        super().__init__()\n",
    "        self.depth = depth\n",
    "        self.thresholds = nn.Parameter(torch.randn(depth))\n",
    "        self.feature_weights = nn.Parameter(torch.randn(depth, in_features))\n",
    "        self.leaf_weights = nn.Parameter(torch.randn(2**depth, d_out))\n",
    "        \n",
    "    def forward(self, x):\n",
    "        splits = []\n",
    "        for i in range(self.depth):\n",
    "            proj = torch.matmul(x, self.feature_weights[i])\n",
    "            split = torch.sigmoid(proj - self.thresholds[i])\n",
    "            splits.append(split.unsqueeze(-1))\n",
    "        splits = torch.cat(splits, dim=-1)\n",
    "        \n",
    "        probs = torch.ones(x.size(0), 1, device=x.device)\n",
    "        for i in range(self.depth):\n",
    "            p_right = splits[:, i].unsqueeze(-1)\n",
    "            p_left = 1.0 - p_right\n",
    "            probs = torch.cat([probs * p_left, probs * p_right], dim=-1)\n",
    "        return torch.matmul(probs, self.leaf_weights).squeeze(-1)\n",
    "\n",
    "class NODE(nn.Module):\n",
    "    def __init__(self, num_numeric, cat_vocab_sizes, depth=4, n_trees=5):\n",
    "        super().__init__()\n",
    "        self.trees = nn.ModuleList([\n",
    "            ObliviousDecisionTree(in_features=num_numeric, depth=depth)\n",
    "            for _ in range(n_trees)\n",
    "        ])\n",
    "        \n",
    "    def forward(self, x_num, x_cat):\n",
    "        preds = [tree(x_num) for tree in self.trees]\n",
    "        return torch.stack(preds, dim=1).mean(dim=1)\n",
    "\n",
    "# 4. Custom Scikit-Learn Compatible Wrapper Class for PyTorch\n",
    "class PyTorchSklearnClassifier(BaseEstimator, ClassifierMixin):\n",
    "    def __init__(self, model_class, lr=0.005, epochs=10, batch_size=512, device=None, **kwargs):\n",
    "        self.model_class = model_class\n",
    "        self.lr = lr\n",
    "        self.epochs = epochs\n",
    "        self.batch_size = batch_size\n",
    "        self.device = device if device is not None else (globals().get('DEVICE') or torch.device('cpu'))\n",
    "        self.kwargs = kwargs\n",
    "        self.model = None\n",
    "        self.classes_ = np.array([0, 1])\n",
    "        \n",
    "    def fit(self, X, y):\n",
    "        if hasattr(X, \"values\"): X_arr = X.values\n",
    "        else: X_arr = np.array(X)\n",
    "        if hasattr(y, \"values\"): y_arr = y.values\n",
    "        else: y_arr = np.array(y)\n",
    "        \n",
    "        num_numeric = X_arr.shape[1]\n",
    "        self.model = self.model_class(num_numeric=num_numeric, cat_vocab_sizes=[], **self.kwargs).to(self.device)\n",
    "        \n",
    "        X_tensor = torch.tensor(X_arr, dtype=torch.float32).to(self.device)\n",
    "        y_tensor = torch.tensor(y_arr, dtype=torch.float32).to(self.device)\n",
    "        \n",
    "        dataset = TensorDataset(X_tensor, y_tensor)\n",
    "        loader = DataLoader(dataset, batch_size=self.batch_size, shuffle=True)\n",
    "        \n",
    "        optimizer = optim.AdamW(self.model.parameters(), lr=self.lr, weight_decay=1e-4)\n",
    "        criterion = nn.BCEWithLogitsLoss()\n",
    "        \n",
    "        self.model.train()\n",
    "        for epoch in range(self.epochs):\n",
    "            for batch_X, batch_y in loader:\n",
    "                optimizer.zero_grad()\n",
    "                preds = self.model(batch_X, torch.zeros(batch_X.size(0), 0, dtype=torch.long, device=self.device))\n",
    "                loss = criterion(preds, batch_y)\n",
    "                loss.backward()\n",
    "                optimizer.step()\n",
    "        return self\n",
    "        \n",
    "    def predict(self, X):\n",
    "        self.model.eval()\n",
    "        if hasattr(X, \"values\"): X_arr = X.values\n",
    "        else: X_arr = np.array(X)\n",
    "        X_tensor = torch.tensor(X_arr, dtype=torch.float32).to(self.device)\n",
    "        with torch.no_grad():\n",
    "            preds = self.model(X_tensor, torch.zeros(X_tensor.size(0), 0, dtype=torch.long, device=self.device))\n",
    "            probs = torch.sigmoid(preds)\n",
    "            return (probs >= 0.5).cpu().numpy().astype(int)\n",
    "            \n",
    "    def predict_proba(self, X):\n",
    "        self.model.eval()\n",
    "        if hasattr(X, \"values\"): X_arr = X.values\n",
    "        else: X_arr = np.array(X)\n",
    "        X_tensor = torch.tensor(X_arr, dtype=torch.float32).to(self.device)\n",
    "        with torch.no_grad():\n",
    "            preds = self.model(X_tensor, torch.zeros(X_tensor.size(0), 0, dtype=torch.long, device=self.device))\n",
    "            probs = torch.sigmoid(preds).cpu().numpy()\n",
    "            return np.vstack([1 - probs, probs]).T\n",
    "\n",
    "# --- LightGBM GPU FALLBACK ENGINE ---\n",
    "if 'TREE_CONFIG' in globals() and 'lgb' in TREE_CONFIG and TREE_CONFIG['lgb'].get('device_type') == 'gpu':\n",
    "    try:\n",
    "        # Attempt to train a trivial model on GPU to verify OpenCL/CUDA compatibility\n",
    "        test_clf = LGBMClassifier(n_estimators=2, device_type='gpu', verbose=-1)\n",
    "        test_clf.fit(np.array([[1.0], [2.0]]), np.array([0, 1]))\n",
    "        print(\"✅ LightGBM GPU acceleration verified successfully.\")\n",
    "    except Exception as e:\n",
    "        print(f\"⚠️ LightGBM GPU acceleration failed: {e}. Falling back to CPU for LightGBM.\")\n",
    "        TREE_CONFIG['lgb'] = {'device_type': 'cpu'}\n",
    "\n",
    "# --- XGBoost n_jobs CUDA FIX ---\n",
    "xgb_n_jobs = -1\n",
    "if 'TREE_CONFIG' in globals() and 'xgb' in TREE_CONFIG and TREE_CONFIG['xgb'].get('device') == 'cuda':\n",
    "    xgb_n_jobs = 1  # Avoid CPU thread conflicts when training on CUDA\n",
    "\n",
    "# Define all models\n",
    "num_threads = os.cpu_count() or 1\n",
    "\n",
    "models = {\n",
    "    'Logistic Regression': LogisticRegression(class_weight='balanced', max_iter=1000, random_state=RANDOM_STATE, solver='lbfgs', n_jobs=-1),\n",
    "    'KNN': KNeighborsClassifier(n_neighbors=5, n_jobs=-1),\n",
    "    'Decision Tree': DecisionTreeClassifier(class_weight='balanced', random_state=RANDOM_STATE),\n",
    "    'Random Forest': RandomForestClassifier(class_weight='balanced', n_estimators=500, random_state=RANDOM_STATE, n_jobs=-1),\n",
    "    'XGBoost': XGBClassifier(scale_pos_weight=(30150/19850), n_estimators=500, random_state=RANDOM_STATE, eval_metric='logloss', **TREE_CONFIG['xgb'], n_jobs=xgb_n_jobs),\n",
    "    'LightGBM': LGBMClassifier(random_state=RANDOM_STATE, n_jobs=-1, verbose=-1, **TREE_CONFIG['lgb']),\n",
    "    'CatBoost': CatBoostClassifier(iterations=500, random_state=RANDOM_STATE, verbose=0),\n",
    "    'FT-Transformer': PyTorchSklearnClassifier(model_class=FTTransformer, epochs=12, lr=0.005),\n",
    "    'SAINT': PyTorchSklearnClassifier(model_class=SAINT, epochs=12, lr=0.005),\n",
    "    'NODE': PyTorchSklearnClassifier(model_class=NODE, epochs=12, lr=0.005),\n",
    "    'Balanced Random Forest': BalancedRandomForestClassifier(n_estimators=500, random_state=RANDOM_STATE, n_jobs=-1),\n",
    "    'Collaborative Filtering (Cosine KNN)': KNeighborsClassifier(n_neighbors=5, metric='cosine', n_jobs=-1),\n",
    "    'Multi-Layer Perceptron': MLPClassifier(hidden_layer_sizes=(128, 64), max_iter=500, random_state=RANDOM_STATE),\n",
    "    'SVM': BaggingClassifier(\n",
    "        estimator=SVC(class_weight='balanced', kernel='rbf', probability=True, random_state=RANDOM_STATE, cache_size=1000, tol=1e-3),\n",
    "        n_estimators=num_threads, max_samples=0.20, n_jobs=-1, random_state=RANDOM_STATE\n",
    "    ),\n",
    "}\n",
    "print(f'Models defined: {list(models.keys())}')\n"
]

# Find the cell and replace it
found = False
for cell in nb["cells"]:
    if cell.get("id") == "216e4ec2":
        cell["source"] = new_source
        found = True
        break

if not found:
    # Try searching by code signature
    for cell in nb["cells"]:
        if cell["cell_type"] == "code" and any("ObliviousDecisionTree" in line for line in cell.get("source", [])):
            cell["source"] = new_source
            found = True
            break

if found:
    with open(notebook_path, "w", encoding="utf-8") as f:
        json.dump(nb, f, indent=1)
    print("Notebook updated successfully.")
else:
    print("Could not find the target cell.")
